Algoritmo "Tabuada"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Aldo henrique
// Descrição   : tabuada
// Autor(a)    : rodrigo de souza
// Data atual  : 21/03/2018
Var
// Seção de Declarações das variáveis
n1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para n1 de 1000 ate 1999 passo 1 faca
se(n1 mod 11=5)entao
 escreval(n1)
 fimse

fimpara

fimalgoritmo