Algoritmo "Tabuada"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Aldo henrique
// Descrição   : tabuada
// Autor(a)    : rodrigo de souza
// Data atual  : 21/03/2018
Var
// Seção de Declarações das variáveis
result,x,y:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para x de 1 ate 10 passo 1 faca
 para y de 1 ate 10 passo 1 faca
  result <- x*y
  escreval(x,"x",y,"=",result)
fimpara
fimpara
fimalgoritmo